### ISSUE TITLE
Silently failing for me

### ISSUE THREAD

**Issue by aaronsarna** [AngeloD2022/onhubauthhelper#1]
I tried following the instructions at https://www.angelod.com/onhubauthtool/ and also using the chrome extension, but, after logging in, both just end of taking me to https://accounts.google.com/embedded/close without showing me anything resembling an oauth token.

I'm a software engineer, with general familiarity with Chrome extensions, so I'm happy to help debug, but I don't know where to start. I couldn't find any meaningful logs from the extension when I went looking.

**Comment by AngeloD2022** [comment]
Do you have any type of ad blocker enabled during the authorization procedure?

**Comment by aaronsarna** [comment]
I did have adblock plus running, but I just tried with it disabled, and got the same result. I've also tried the manual method in both Firefox and Safari, which have no extensions running, and also got the same result.

**Comment by AngeloD2022** [comment]
That is certainly strange. Could you go into a bit more detail about how the manual method failed for you? Would you mind opening the developer tools and inspect the communication with google, and letting me know if there is some error? The issue, in nature, seems specific to your account.

**Comment by aaronsarna** [comment]
I don't see any errors. All of the network calls have status 200. There are no errors in the console.

Does the "device name" matter? If so, what should I be setting it to?

**Comment by AngeloD2022** [comment]
The device name does not matter. On the manual method, does the consent screen not return any oauth code cookie?

**Comment by aaronsarna** [comment]
Ah I do see an oauth_code in the set-cookie response header of the /challenge request. Didn't realize I was supposed to look there.

**Comment by aaronsarna** [comment]
I'm trying to use the code in https://github.com/AngeloD2022/onhubauthhelper/blob/master/js/tokenPage.js to issue the request for the refresh token using the value of the oauth_code cookie, but it just responds with: 
```
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

**Comment by aaronsarna** [comment]
Same result when pasting the oauth_code into https://www.angelod.com/onhubauthtool/

**Comment by AngeloD2022** [comment]
Are you using the Google account associated with your WiFi System?

**Comment by aaronsarna** [comment]
So the answer to your question is yes, but it led me to what I think must be the issue, which is that I'm logged into 3 different Google accounts at once, and only 1 of them is associated with the Wifi. I reran the manual method in an incognito window, so I would only log in to the relevant account, and then it worked. Might be worth mentioning in the documentation that there are problems around multi-login.

As a side note, it wasn't totally clear to me from the manual instructions that I was supposed to be looking for a cookie that got set. The instructions could be improved a bit.

**Comment by AngeloD2022** [comment]
> I reran the manual method in an incognito window, so I would only log in to the relevant account, and then it worked.

That's certainly odd. It works on my configuration in the same scenario, but I am glad that your issue has been resolved.

>  it wasn't totally clear to me from the manual instructions that I was supposed to be looking for a cookie that got set. The instructions could be improved a bit.

I appreciate the feedback. Could you expand on this?

**Comment by aaronsarna** [comment]
I suppose it could also be an extension I have running that isn't present in incognito.

I would update the text "Copy the oauth_code after signing in using the URL." to something like "Sign in using the URL, then find the cooking named 'oauth_code' for site 'accounts.google.com' and copy its content here." If you want to be extra friendly you could provide instructions for how to find the cookie contents in a number of different browsers, but maybe those users should stick to the Chrome extension.

I wonder if it would be worth digging more into what happened with my case, where the Chrome extension didn't even open the new window after login, so it seemed like it wasn't doing anything at all. I'd hope there could be at least an error message displayed.
