### ISSUE TITLE
Permission denied on GET Devices

### ISSUE THREAD

**Issue by KonradJanica** [AngeloD2022/onhubauthhelper#5]
I'm trying the following GET Devices API - https://documenter.getpostman.com/view/7490211/SzzdD1pF?version=latest#5ebda19e-80d1-4fa6-8ba9-a678573f4596

I used your latest update to successfully retrieve a refresh token and I generated an API Token following the instructions, but I receive the following error response when calling `https://googlehomefoyer-pa.googleapis.com/v2/groups/:systemId/stations?prettyPrint=false`. 

```
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

Any idea what I am doing wrong? Interestingly enough when I accidentally used my REFRESH_TOKEN, I got the following response:
```
{
  "error": {
    "code": 403,
    "message": "Home Foyer API has not been used in project ######### before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/googlehomefoyer-pa.googleapis.com/overview?project=########### then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/googlehomefoyer-pa.googleapis.com/overview?project=##########"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "SERVICE_DISABLED",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/#########",
          "service": "googlehomefoyer-pa.googleapis.com"
        }
      }
    ]
  }
}
```

**Comment by AngeloD2022** [comment]
I have never experienced something like this. Are you using the right Google account?

**Comment by KonradJanica** [comment]
I managed to get it working using the Android APIs, I think the problem is that my account is not associated with an iOS device or something. Thanks for the help!
