### ISSUE TITLE
Any chance of Google Advanced Protection support in future?

### ISSUE THREAD

**Issue by fctruter** [AngeloD2022/onhubauthhelper#7]
According to the FAQs, Google automatically disables app access entirely if you enroll for the Google Advanced Protection program.

https://support.google.com/accounts/answer/7539956?hl=en#zippy=%2Ccan-i-still-use-app-passwords 

I know this is a long shot, but is there any chance you could work around this in the future? It seems a shame to lose access to this great integration, but it seems to be quite a bit more secure. I suppose I could use a secondary non-secure Gmail account to administer my google WiFi, just thought I'd ask anyway.

**Comment by AngeloD2022** [comment]
Can you provide a screenshot of the problem you have encountered with 2FA?

**Comment by fctruter** [comment]
I managed to resolve this by just going through all the steps to get a new refresh token. I just thought that because the old refresh token stopped working I couldn't get a new one, but luckily it works perfectly now, thanks!
